### ISSUE TITLE
Added tags on top

### ISSUE THREAD

**Issue by meets2tarun** [niccokunzmann/fossasia-badge-generator#11]
Please add tag as python and make description as Camel Case

**Comment by meets2tarun** [comment]
Please add the tag and close the issue.

**Comment by niccokunzmann** [comment]
@meets2tarun Do you mean to say that I should add a tag? Where should I add a tag? Do you mean repository topic?

**Comment by meets2tarun** [comment]
@niccokunzmann  Yes, you should add the tag for description of the languages used in the project.
You can add on the top, just below the code tab.
Yeah repository topic.

**Comment by niccokunzmann** [comment]
@meets2tarun Can you see them? Like this? Which badges would you add?

**Comment by meets2tarun** [comment]
@niccokunzmann Now its fine.
Now please change the description in Camel Case form. 
From `conference badges generator for fossasia`
to `Conference Badges Generator of FOSSASIA`
What do you think ?

**Comment by niccokunzmann** [comment]
Sure! Thanks for the clear formulation! I was not sure what you meant.

**Comment by meets2tarun** [comment]
Thanks...
