### ISSUE TITLE
Create LICENSE file

### ISSUE THREAD

**Issue by niccokunzmann** [niccokunzmann/fossasia-badge-generator#6]
Without a license this is not legally usable by others.
@meets2tarun To which license would you agree?

- GPLv3
- MIT

Or any other?

You can create a pull-request with a LICENSE file in the root directory. Github provides the license text.
I will merge, so we see that we both agree in the git history.
What do you think?

**Comment by meets2tarun** [comment]
Fine, I will soon make a PR.

**Comment by niccokunzmann** [comment]
Thanks! It is a pleasure working with you :)
